name: check_pr

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Install requirements
      run: |
        sudo apt-get update
        sudo apt-get install -y libgdal-dev
        pip install --no-cache-dir pipenv
        pipenv install --dev
    - name: run lint
      run: make test-ci


  dockerize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build the docker-compose stack
        run: docker-compose up -d
      - name: Sleep
        uses: jakejarvis/wait-action@master
        with:
          time: '20s'
      - name: Check db migrate on container
        run: |
          docker-compose exec -T club_app make docker-migrate
      - name: Check build frontend on container
        run: |
          docker-compose exec -T webpack npm run build
